import ProjectDescription

let appName = "Learn"

let appSchemes: [Scheme] = [
  .scheme(
    name: appName + "-Debug",
    shared: true,
    buildAction: .buildAction(targets: [.project(path: "iOS", target: appName)]),
    runAction: .runAction(
      configuration: "Debug", 
      executable: .project(path: "iOS", target: appName))
  ),
  .scheme(
    name: appName + "-Staging",
    shared: true,
    buildAction: .buildAction(targets: [.project(path: "iOS", target: appName)]),
    runAction: .runAction(
      configuration: "Release-Staging", 
      executable: .project(path: "iOS", target: appName)
    )
  ),
  .scheme(
    name: appName + "-Production",
    shared: true,
    buildAction: .buildAction(targets: [.project(path: "iOS", target: appName)]),
    runAction: .runAction(
      configuration: "Release-Production", 
      executable: .project(path: "iOS", target: appName)
    )
  ) 
]

let workspace = Workspace(
  name: "Learn",
  projects: ["iOS"],
  schemes: appSchemes,
  generationOptions: .options(
    autogeneratedWorkspaceSchemes: .disabled
  )
)